# Generated by Django 5.1.7 on 2025-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="create_date",
            field=models.DateTimeField(),
        ),
    ]
